### PR TITLE
Add a protocol NIVisuallyRepressibleObject that can be conformed to by objects to annotate whether their visibility is repressed.

### PR DESCRIPTION
**Pull request by samircy7**
This concept is common in A/B testing wherein a visual element may be shown in an experimental arm but hidden in the control arm.

### CODE REVIEW

**Comment by stephanemoore** [comment]
I wonder if it might help to include more of the downstream commits so that we have more of a sense of the longterm direction that this proposal aims towards?

**Comment by samircy7** [comment]
> I wonder if it might help to include more of the downstream commits so that we have more of a sense of the longterm direction that this proposal aims towards?

I thought so too, but I wanted to get this in sooner because this protocol is being requested by a couple of other folks, since it can be used outside of the larger proposal for visually repressing collection view items, and I haven't completed the work on the other parts yet.

**Comment by samircy7** [comment]
> Without a better understanding of the broader context of this change my gut feeling is that this is out of scope for Nimbus’ models solution.
> 
> My rationale: I’d expect an A/B testing library to define the protocol proposed here. The library would then accept a collection of objects that conform to this protocol as an input and return a collection of objects with visually repressed objects filtered out. This controller wouldn’t necessarily have to be aware of the Nimbus types with this design, just the concept of a collection of model objects. The returned collection of objects could then be used to create a Nimbus model.
> 
> I’m marking as changes requested pending further context that affects my gut feeling here.

Thanks for the review! The end goal of this effort is to have other model classes in Nimbus (NICollectionViewModel in this case) support the concept of visually repressed objects. The objective is to make it convenient for developers that use NICollectionViewModel as their collection views' data source to not have to worry about handling visually repressed objects manually. By supporting visually repressible objects, NICollectionViewModel would be able to accept both regular and visually repressed objects, but it will still vend out only visible objects to the collection view and will internally store a reference to all the visually repressed objects. The repressed objects can then be referenced using convenience methods.

The issue with having a separate filtering class is that we care about the exact position of the visually repressible object in the collection view model, and so we will be required to generate some kind of mapping to determine where exactly a visually repressed object is positioned given an array of regular objects. This mapping would then have to be adjusted in the case of mutable collection view models. The hope was that this could be significantly simplified by having the model class filter the visually repressed objects internally.

**Comment by leovitch** [comment]
I have some more context on what samircy7 is trying to do here, but even given my extra context this is very hard to evaluate given this very small pull request.  As stephanemoore suggested, it might make more sense to expose downstream pull requests to understand why this is or isn't in scope for Nimbus.

**Comment by jverkoey** [comment]
@samircy7 @stephanemoore and I had a quick offline chat to discuss the context. Based on that discussion, @samircy7 will be exploring an alternate approach that involves extracting the Nimbus Models pattern as a protocol to which custom implementations can be built. This custom protocol will be proposed as an additional API to Nimbus.

**Comment by jverkoey** [comment]
The discussions from this pull request have resulted in https://github.com/jverkoey/nimbus/pull/697 which is now merged, so I'll be closing this PR.

**Pull request closed without merging**
